# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freeplane.protoc
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66reeplane.protoc\x12\tfreeplane\"\"\n\x12\x63reateChildRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x13\x63reateChildResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2[\n\tFreeplane\x12N\n\x0b\x63reateChild\x12\x1d.freeplane.createChildRequest\x1a\x1e.freeplane.createChildResponse\"\x00\x42-\n\x19org.freeplane.plugin.grpcB\tfreeplaneP\x01\xa2\x02\x02\x46Pb\x06proto3')



_CREATECHILDREQUEST = DESCRIPTOR.message_types_by_name['createChildRequest']
_CREATECHILDRESPONSE = DESCRIPTOR.message_types_by_name['createChildResponse']
createChildRequest = _reflection.GeneratedProtocolMessageType('createChildRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHILDREQUEST,
  '__module__' : 'freeplane.protoc_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.createChildRequest)
  })
_sym_db.RegisterMessage(createChildRequest)

createChildResponse = _reflection.GeneratedProtocolMessageType('createChildResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHILDRESPONSE,
  '__module__' : 'freeplane.protoc_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.createChildResponse)
  })
_sym_db.RegisterMessage(createChildResponse)

_FREEPLANE = DESCRIPTOR.services_by_name['Freeplane']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.freeplane.plugin.grpcB\tfreeplaneP\001\242\002\002FP'
  _CREATECHILDREQUEST._serialized_start=31
  _CREATECHILDREQUEST._serialized_end=65
  _CREATECHILDRESPONSE._serialized_start=67
  _CREATECHILDRESPONSE._serialized_end=105
  _FREEPLANE._serialized_start=107
  _FREEPLANE._serialized_end=198
# @@protoc_insertion_point(module_scope)
