classes:
  - kafka
  - helm
parameters:

  kapitan:
    dependencies:
      - source: https://github.com/jsonnet-libs/strimzi-libsonnet/
        type: git
        output_path: files/github.com/jsonnet-libs/strimzi-libjsonnet
        ref: 45207bb16595acf8b3218d98841137f89df793ae
      - type: helm
        source: https://strimzi.io/charts/
        chart_name: strimzi-kafka-operator
        output_path: files/helm-charts/strimzi-kafka-operator
        version: 0.32.0

  strimzi_jsonnet_version: 0.32


  tmuxinator:
    windows:
      strimzi:
        panes:
          -
            - cd ${kapitan_root}/jsonnet/strimzi
          -
            - cd ${kapitan_root}/files/helm-charts/strimzi-kafka-operator
