---
parameters:
  bash:
    functions:
      tmux_session_start: >
        TMUXINATOR_CONFIG=${compiled_dir} tmuxinator start tmuxinator
        tmux attach -t ${target_name}
  kapitan:
    compile:
      - input_type: jsonnet
        input_paths:
          - jsonnet/tmuxinator.jsonnet
        output_path: .
        output_type: "yml"
  tmuxinator:
    name: ${target_name}
