parameters:  
  tmuxinator:
    root: ${compiled_dir}
    windows:
      - kapitan:
          layout: main-vertical
          pre:
            - |
              . ${compiled_dir}/functions.bash
          panes:
            - |
              kapitan_edit_target
            - |
              echo kapitan_compile
            # TODO metacoma nix-shell XXX
            - |
              nix-shell -p entr
              cd ${kapitan_root}
              find ${kapitan_root}/inventory/targets/ -type f -iname "${target_name}.yml" | entr -p -c sh -c "./kapitan.sh compile -t ${target_name}"
