parameters:
  tmuxinator:
    root: ${compiled_dir}
    windows:
      kapitan:
        layout: main-vertical
        panes:
          - |
            kapitan_edit_target
          - |
            echo kapitan_compile
          # TODO metacoma nix-shell XXX
          - |
            cd ${kapitan_root}
            (
              find inventory/targets/ -type f -iname '${target_name}.yml';
              kapitan_inventory | yq -r '.parameters.kapitan.compile[].input_paths[]'
            ) | entr -p -c bash -c ". ${compiled_dir}/functions.bash && kapitan_compile"
