---
classes:
#  - vector
#  - kafka
parameters:
  kapitan:
    compile:
      - input_paths:
          - files/vector/pipe-pane2hexstream.pl
        output_path: .
        input_type: copy

  vector:
    config:
      tmux-bytestream:
        sources:
          tmux-bytestream:
            type: "file_descriptor"
            fd: 0
            decoding:
              codec: "bytes"

        sinks:
          tmux-to-vector:
            type: socket
            mode: tcp
            inputs:
              - tmux-bytestream
            address: \${VECTOR_UPSTREAM}
            encoding:
              codec: json
