---
classes:
  - vector
  - kafka
parameters:
  vector:
    config:
      tmux-kafka:
        sources:
          stdin:
            type: "stdin"
            decoding:
              codec: "bytes"
        transforms:
          lua:
            inputs:
              - stdin
            type: "lua"
            # 2022-12-26T00:51:06.650157Z ERROR vector::cli: Configuration error. error=data did not match any variant of untagged enum LuaConfig for key `transforms.lua`
            # https://github.com/serde-rs/serde/issues/773#issuecomment-777314431
            version: "2"
            hooks:
              process: |
                function (event, emit)
                  emit(event)
                end
        sinks:
          tmux-raw-stream:
            type: kafka
            inputs:
              - lua
            bootstrap_servers: "${kafka:host}:${kafka:port}"
            topic: ${kafka_tmux_topic}
            compression: "none"
            encoding:
              codec: json

