---
classes:
#  - vector
#  - kafka
parameters:
  kapitan:
    compile:
      - input_paths:
          - files/vector/pipe-pane2hexstream.pl
        output_path: .
        input_type: copy

  vector:
    config:
      tmux-bytestream:
        sources:
          tmux-raw-bytestream:
            type: "file_descriptor"
            fd: 0
            decoding:
              codec: "bytes"
        transforms:
          tmux-bytestream:
            type: remap
            inputs:
              - tmux-raw-bytestream
            source: |
              .tmux_pane_id = "\${TMUX_PANE_ID}"
        sinks:
          tmux-to-vector:
            type: vector

            inputs:
              - tmux-bytestream
            address: \${VECTOR_UPSTREAM}
            version: "2"
            acknowledgements:
              enabled: false

