---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator
  - tmuxinator.kapitan
#  - tmuxp

parameters:



  target_name: fluentd

  fluentd_named_pipe_plugin: files/git/metacoma/fluent-plugin-named_pipe

  fluentd:
    version: 1.15
    docker:
      image:
        repo: fluent/fluentd
        tag: v${fluentd:version}-debian-1

  bash:
    functions:
      kapitan_compile: |
        cd ${kapitan_root}
        ./kapitan.sh compile --fetch -t ${target_name}
      fluentd_start: |
        docker run --rm -it \
          --network host \
          -v ${kapitan_root}/${fluentd_named_pipe_plugin}:/tmp/fluentd_named_pipe_lugin \
          -v ${mindwm:runtime:root}:${mindwm:runtime:root} \
          ${fluentd:docker:image:repo}:${fluentd:docker:image:tag}
      fluentd_stop:
        echo fluentd_stop
      fluentd_restart:
        echo fluentd_restart


  kapitan:
    dependencies:
      # workaround for https://github.com/sonots/fluent-plugin-named_pipe/pull/9
      - type: git
        output_path: ${fluentd_named_pipe_plugin}
        source: https://github.com/metacoma/fluent-plugin-named_pipe.git
        ref: without_mkfifo_dependency


  tmuxinator:
    name: ${target_name}
    root: ${compiled_dir}

    windows:
      - shell:
          layout: main-vertical
          # TODO (@metacoma) move 'pre' section in jsonnet template
          pre:
            - |
              . ${compiled_dir}/functions.bash
          panes:
            - |
              fluentd_start
