---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator
  - tmuxinator.kapitan
#  - tmuxp

parameters:

  target_name: freeplane-node
  node_id: ${target_name}

  # fifo
  tmux_fifo: ${mindwm:runtime:tmux_dir}/tmux-${node_id}.fifo
  # for some reason, fluentd will fail with other umask
  # 2022-12-20 05:14:10 +0000 [error]: config error file="/etc/fluentd/tmux.conf" error_class=Fluent::ConfigError error="Errno::EACCES: Permission denied @ rb_sysopen - /tmp/mindwm/tmux/tmux-ID_184313.fifo"
  fifo_umask: 0000

  tmuxinator:
#     name: freeplane-node-${node_id}  
    root: ${compiled_dir}

    startup_window: shell

    windows:
      - shell:
          layout: main-vertical
          # TODO (@metacoma) move 'pre' section in jsonnet template
          pre:
            - |
              . ${compiled_dir}/functions.bash
          panes:
            - |
              mkdir -p ${mindwm:runtime:tmux_dir}
              test -p ${tmux_fifo} -o -f ${tmux_fifo} && rm -v ${tmux_fifo}
              mkfifo -m ${fifo_umask} ${tmux_fifo}
              tmux pipe-pane -IO -t ${tmuxinator:name}:1 "cat > ${tmux_fifo}"
