classes:
  - common
  - mindwm
  - freeplane
  - vim
  - tmuxinator
  - bash.kapitan
  - kapitan.bash.compile-fetch
  - tmuxinator.kapitan
  - terminal.emulator.xterm
  - freeplane.lib.fp
  - freeplane.scripts.kapitan-node

parameters:
  target_name: freeplane

  bash:
    functions:
      freeplane_start: |
        cd ${freeplane_root}
        sed -i 's,^userfpdir=.*,userfpdir="${freeplane_root}",' ./freeplane.sh
        bash ./freeplane.sh


  kapitan:
    dependencies:
      - type: http
        output_path: .
        source: https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-${freeplane_version}.zip/download
        unpack: true
      - type: http
        source: https://github.com/metacoma/freeplane_plugin_grpc/releases/download/${freeplane_plugin_grpc_version}/org.freeplane.plugin.grpc.zip
        output_path: ${freeplane_root}/plugins/
        unpack: true

  tmuxinator:
    windows:
      freeplane:
        panes:
          - cd ${freeplane_root}/
          - cd ${freeplane_root}/
      scripts:
        panes:
          - cd ${freeplane_root}/scripts
          - cd ${freeplane_root}/scripts

