classes:
  - common
  - mindwm
  - freeplane
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator.kapitan
  - terminal.emulator.xterm
  - freeplane.lib.fp
  - freeplane.scripts.kapitan-node

parameters:
  target_name: freeplane

  bash:
    functions:
      kapitan_compile: |
        cd ${kapitan_root}
        ./kapitan.sh compile --fetch --cache -t ${target_name}
      freeplane_start: |
        cd ${freeplane_root}
        sed -i 's,^userfpdir=.*,userfpdir="${freeplane_root}",' ./freeplane.sh
        bash ./freeplane.sh


  kapitan:
    dependencies:
      - type: http
        output_path: .
        source: https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-${freeplane_version}.zip/download
        unpack: true

  tmuxinator:
    windows:
      freeplane:
        panes:
          - cd ${freeplane_root}/
          - cd ${freeplane_root}/
      scripts:
        panes:
          - cd ${freeplane_root}/scripts
          - cd ${freeplane_root}/scripts

