---
classes:
  - common
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator.kapitan
  - kapitan.bash.compile-fetch
  - kafka

  - kafka.topic.tmux-pane-bytestream
  - kafka.topic.tmux-pane-linestream
  - kafka.topic.tmux-pane-io-context

  - kafka.topic.tmux-pane-raw-linestream
  - kafka.topic.tmux-pane-raw-io-context

  - helm
  - kafka.ui

  - kafka.strimzi
  - kafka.strimzi.topic
  - kafka.strimzi.cluster
parameters:
  target_name: kafka

  bash:
    functions:
      # move to strimzi.kafka-cluster class
      strimzi_delete_cluster: |
        local ns=\${1}
        kubectl delete -f 'https://strimzi.io/install/latest?namespace=kafka' -n \${ns}
        return
        kubectl -n \${ns} delete $(kubectl get strimzi -n \${ns} -o name)
      strimzi_cluster_deploy: |
        local ns=\${1}
        kubectl -n \${ns} apply -f ${compiled_dir}/strimzi/cluster/mindwm.yaml
      strimzi_topic_create: |
        local ns=\${1}
        kubectl -n \${ns} apply -f ${compiled_dir}/strimzi/topic/*.yaml
      strimzi_uninstall: |
        local ns=\${1}
        kubectl -n \${ns} delete configmap -l app.kubernetes.io/instance=${kafka_cluster_name} -l app.kubernetes.io/managed-by=strimzi-cluster-operator
        kubectl -n \${ns} delete crds -l 'app=strimzi'
        kubectl -n \${ns} delete deployment -l 'app=strimzi'
        # FIXME -l
        kubectl -n kafka delete serviceaccount strimzi-cluster-operator
        kubectl -n kafka delete configmap -l app=strimzi

      delete_cluster: |
        local ns=${kafka_k8s_namespace}
        strimzi_delete_cluster \${ns}
      kafka_cluster_deploy: |
        local ns=${kafka_k8s_namespace}
        strimzi_cluster_deploy \${ns}
      kafka_topic_create: |
        strimzi_topic_create ${kafka_k8s_namespace}
      kafka_uninstall: |
        local ns=${kafka_k8s_namespace}
        strimzi_uninstall \${ns}

      kafka_helm_install: |
        helm upgrade --install --namespace ${kafka_k8s_namespace} ${kafka_cluster_name} ${kapitan_root}/files/helm-charts/strimzi-kafka-operator

      kafka_helm_deinstall:
        helm uninstall --namespace ${kafka_k8s_namespace} ${kafka_cluster_name}

  tmuxinator:
    windows:
      kafka-connect:
        panes:
          - 'kubectl run kafka-consumer -ti --image=quay.io/strimzi/kafka:0.32.0-kafka-3.3.1 --rm=true --restart=Never -- bin/kafka-console-consumer.sh --bootstrap-server ${kafka_cluster_name}-kafka-external-0.${kafka_k8s_namespace}:${kafka_port} --topic tmux-pane-bytestream --from-beginning'
          -
#      host-consumers:
#        pre:
#          - cd ${kapitan_root}/files/kafka
#          - . .venv/bin/activate
#        panes:
#          # this "host" consumer remove the color codes from the io-context events
#          -
#            - python ./kafka-tmux-pane-raw-io-context.py
#          # this "host" consumer remove the color codes from the lines events
#          -
#            - python ./kafka-tmux-pane-raw-linestream.py


