---
classes:
  - common
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator.kapitan
  - kapitan.bash.compile-fetch
  - kafka

  - kafka.topic.tmux-pane-bytestream
  - kafka.topic.tmux-pane-linestream
  - kafka.topic.tmux-pane-io-context

  - kafka.strimzi
  - kafka.strimzi.topic
  - kafka.strimzi.cluster
parameters:
  target_name: kafka

  bash:
    functions:
      # move to strimzi.kafka-cluster class
      strimzi_delete_cluster:
        local ns=${kafka_k8s_namespace}
        kubectl -n \${ns} delete $(kubectl get strimzi -n \${ns} -o name)
      delete_cluster:
        local ns=${kafka_k8s_namespace}
        strimzi_delete_cluster \${ns}





