---
classes:
  - common
  - docker.image

  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator.kapitan
parameters:
  target_name: kapitan

  kapitan:
    dependencies:
      - type: git
        output_path: compiled/${target_name}/kapitan
        source: https://github.com/metacoma/kapitan
        #subdir: relative/path/from/repo/root (optional)
        #ref: tag, commit, branch etc. (optional)

  docker:

    from:
      image: alpine
      tag: 3.17.0

    image:
      name: kapitan
      tag: mindwm

    # Dockerfile
    file: |
      echo "hello world"
       
