classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - tmuxinator.kapitan
  - bash.kapitan
  - kapitan.bash.compile-fetch


parameters:
  target_name: kubernetes

  bash:
    functions:
      kubectl_get_service_nodeport: |
        # usage
        # kubectl_get_service_nodeport kafka mindwm-kafka-external-0
        kubectl get svc -n $* --output='jsonpath="{.spec.ports[0].nodePort}"'


  tmuxinator:
    windows:
      kubectl:
        panes:
          - kubectl get all --all-namespaces
          -

  notes:
    port_range_example: |
      minikube start --extra-config=apiserver.service-node-port-range=1-65535
