classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - tmuxinator.kapitan
  - bash.kapitan
  - kapitan.bash.compile-fetch


parameters:
  target_name: kubernetes


  kapitan:
    dependencies:
      - type: git
        source: https://github.com/ansible/awx
        output_path: files/github.com/ansible/awx
        ref: "21.10.2"

  bash:
    functions:
      kubectl_get_service_nodeport: |
        # usage
        # kubectl_get_service_nodeport kafka mindwm-kafka-external-0
        kubectl get svc -n $* --output='jsonpath="{.spec.ports[0].nodePort}"'


  tmuxinator:
    windows:
      kubectl:
        panes:
          - kubectl get all --all-namespaces
          -

  notes:
    port_range_example: |
      minikube start --extra-config=apiserver.service-node-port-range=1-65535
