---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator
  - tmuxinator.kapitan
  - kapitan.bash.compile-fetch
  - helm
  - opensearch
  - opensearch.helm
  - opensearch.dashboards.helm
#  - tmuxp

parameters:

  docker_image_name: opensearchproject/opensearch
  docker_image_tag: 2.4.1

  docker_dashboards_image_name: opensearchproject/opensearch-dashboards
  docker_dashboards_image_tag: 2.4.1

  target_name: opensearch

  opensearch_port: 31002
  # opensearch_k8s_namespace: opensearch

  tmuxinator:
    name: ${target_name}
    root: ${compiled_dir}

    startup_window: opensearch

    windows:
      opensearch:
        layout: main-horizontal
        panes:
          - |
            while :; do
              opensearch_logs
              sleep 1
            done
          - |
            while :; do
              opensearch_pod
              sleep 1
            done
      dashboards:
        layout: main-horizontal
        panes:
          -

          -
