---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - bash.script
  - tmuxinator
  - tmuxinator.kapitan
  - kapitan.bash.compile-fetch
  - helm
  - opensearch
  - opensearch.index_patterns
  - opensearch.helm
    #  - opensearch.dashboards
  - opensearch.dashboards.helm
  - wtf
#  - tmuxp

parameters:

  docker_image_name: opensearchproject/opensearch
  docker_image_tag: 2.4.1

  docker_dashboards_image_name: opensearchproject/opensearch-dashboards
  docker_dashboards_image_tag: 2.4.1

  target_name: opensearch

  opensearch_port: 31002
  # opensearch_k8s_namespace: opensearch
  bash:
    functions:

      opensearch_api_endpoint: |
        minikube service -n opensearch opensearch-cluster-master --url | sed -n '1s/^http/https/g p'
      opensearch_wait_200: |
        local endpoint=`opensearch_api_endpoint`
        while :; do
          echo -n .
          http_code=`curl -k -u ${opensearch_api_user}:${opensearch_api_password} -s -o /dev/null \${endpoint} -w "%{http_code}"`
          if [ \${http_code} -ge "200" -a \${http_code} -lt 300 ]; then
            break
          fi
        done

      opensearch_curl: |
        curl -s -k -u vector:vectorvector `opensearch_api_endpoint`/$1
      opensearch_health: |
        opensearch_curl "_cluster/health?wait_for_status=yellow&timeout=50s" | jq '.status'

  wtf:
    mods:
      health:
        cmd: "bash"
        args:
          - "${compiled_dir}/bin/opensearch_health.sh"
        enabled: true
        position:
          top: 0
          left: 0
          height: 3
          width: 3
        refreshInterval: 5s
        type: cmdrunner

  tmuxinator:
    name: ${target_name}
    root: ${compiled_dir}

    startup_window: opensearch

    windows:
      opensearch:
        layout: main-horizontal
        panes:
          - |
            while :; do
              opensearch_logs
              sleep 1
            done
          - |
            while :; do
              opensearch_pod
              sleep 1
            done
      dashboards:
        layout: main-horizontal
        panes:
          -

          -
