---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator
  - tmuxinator.kapitan
  - logstash
  - kapitan.bash.compile-fetch
  - kafka
  - vector
  - vector.tmux-bytestream-kafka
#  - vector.tmux-kafka
#  - vector.console-output
  - vector.config
  - vector.helm

parameters:

  target_name: vector


  bash:
    functions:
      kapitan_compile: |
        cd ${kapitan_root}
        ./kapitan.sh compile --fetch -t ${target_name}
      # https://vector.dev/docs/setup/installation/package-managers/nix/
      vector_upgrade: |
        local values_file=\${1:-${compiled_dir}/vector_helm/values.yaml}
        (
          cd ${kapitan_root}/files/helm-charts/vector
          helm upgrade vector --install -n ${vector_k8s_ns} . -f ${compiled_dir}/vector_helm/values.yaml $*
        )
      vector_values: |
        (
          cd ${kapitan_root}/files/helm-charts/vector
          vim -R values.yaml
        )
      vector_logs: |
        (
          kubectl -n ${vector_k8s_ns} logs -f vector-0
        )

  vector_aggregator_port: 31399

  vector:
    aggregator:
      image:
        repository: ${vector_image:repo}
        tag: ${vector_image:tag}
      serviceHeadless:
        enabled: false
      service:
        enabled: True
        type: "NodePort"
        ports:
          - name: aggregator
            protocol: TCP
            port: ${vector_aggregator_port}
            targetPort: ${vector_aggregator_port}
            nodePort: ${vector_aggregator_port}
      customConfig:
        sources:
          tmux-bytestream:
            type: socket
            mode: tcp
            address: 0.0.0.0:${vector_aggregator_port}
        sinks:
          kafka:
            type: kafka
            inputs:
              - tmux-bytestream
            bootstrap_servers: "mindwm-kafka-external-bootstrap.kafka:9092"
            topic: " tmux-pane-bytestream"
            compression: "none"
            encoding:
              codec: json

  tmuxinator:
    windows:
      helm:
        panes:
          - cd ${kapitan_root}/files/helm-charts/vector
          - cd ${kapitan_root}/files/helm-charts/vector
      shell:
        panes:
          -
            - tmux pipe-pane -IO "perl ${compiled_dir}/pipe-pane2hexstream.pl | export VECTOR_UPSTREAM=`minikube ip`:${vector_aggregator_port} vector -q --config ${compiled_dir}/vector/tmux-bytestream.yaml"
          -
            -

