---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator
  - tmuxinator.kapitan
  - logstash
  - kapitan.bash.compile-fetch
#  - kafka
#  - vector.tmux-bytestream-kafka
#  - vector.tmux-kafka
#  - vector.console-output

parameters:

  target_name: vector


  bash:
    functions:
      kapitan_compile: |
        cd ${kapitan_root}
        ./kapitan.sh compile --fetch -t ${target_name}
      # https://vector.dev/docs/setup/installation/package-managers/nix/
      vector_install: |
        nix-env --install \
          --file https://github.com/NixOS/nixpkgs/archive/master.tar.gz \
            --attr vector

      vector_start: |
        echo vector start
