---
classes:
  - common
  - mindwm
  - vim
  - tmuxinator
  - bash.kapitan
  - tmuxinator
  - tmuxinator.kapitan
  - logstash
  - kapitan.bash.compile-fetch
  - kafka
  - vector.tmux-bytestream-kafka
  - vector.tmux-kafka
  - vector.console-output

parameters:

  target_name: vector


  bash:
    functions:
      kapitan_compile: |
        cd ${kapitan_root}
        ./kapitan.sh compile --fetch -t ${target_name}
      # https://vector.dev/docs/setup/installation/package-managers/nix/
      vector_install: |
        nix-env --install \
          --file https://github.com/NixOS/nixpkgs/archive/master.tar.gz \
            --attr vector

      vector_start: |
        echo vector start

#  vector:
#    config:
#      console-output:
#        sources:
#          tmux:
#            port: 4001

  tmuxinator:
    name: ${target_name}
    root: ${compiled_dir}

    startup_window: shell




    windows:
      kafka-topic:
        layout: main-vertical
        # TODO (@metacoma) move 'pre' section in jsonnet template
        pre:
          - |
            . ${compiled_dir}/functions.bash
        panes:
          - |
            kcat -b ${kafka:host}:${kafka:port} -t ${kafka_tmux_topic}
          - |
            cd ${kapitan_root}/files/vector
      shell:
        pre:
          - |
            . ${compiled_dir}/functions.bash
        panes:
          # run vector for the debug purposes
          - |
            vector --config vector/console-output.yaml

         # i spent a lot(LOT) of time for this one-liner, stuck here for four(4) days
         # https://www.unix.com/shell-programming-and-scripting/210907-grab-exactly-one-byte-fifo-random-intervals.html
          - |
            tmux pipe-pane -IO 'perl ${compiled_dir}/pipe-pane2hexstream.pl | vector -q --config ${compiled_dir}/vector/tmux-bytestream-kafka.yaml'
