# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freeplane.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66reeplane.proto\x12\tfreeplane\"\"\n\x12\x43reateChildRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"9\n\x13\x43reateChildResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tnode_text\x18\x02 \x01(\t\"%\n\x12\x44\x65leteChildRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"&\n\x13\x44\x65leteChildResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"Y\n\x17NodeAttributeAddRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x15\n\rproperty_name\x18\x02 \x01(\t\x12\x16\n\x0eproperty_value\x18\x03 \x01(\t\"+\n\x18NodeAttributeAddResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8a\x02\n\tFreeplane\x12N\n\x0b\x43reateChild\x12\x1d.freeplane.CreateChildRequest\x1a\x1e.freeplane.CreateChildResponse\"\x00\x12N\n\x0b\x44\x65leteChild\x12\x1d.freeplane.DeleteChildRequest\x1a\x1e.freeplane.DeleteChildResponse\"\x00\x12]\n\x10NodeAttributeAdd\x12\".freeplane.NodeAttributeAddRequest\x1a#.freeplane.NodeAttributeAddResponse\"\x00\x42-\n\x19org.freeplane.plugin.grpcB\tfreeplaneP\x01\xa2\x02\x02\x46Pb\x06proto3')



_CREATECHILDREQUEST = DESCRIPTOR.message_types_by_name['CreateChildRequest']
_CREATECHILDRESPONSE = DESCRIPTOR.message_types_by_name['CreateChildResponse']
_DELETECHILDREQUEST = DESCRIPTOR.message_types_by_name['DeleteChildRequest']
_DELETECHILDRESPONSE = DESCRIPTOR.message_types_by_name['DeleteChildResponse']
_NODEATTRIBUTEADDREQUEST = DESCRIPTOR.message_types_by_name['NodeAttributeAddRequest']
_NODEATTRIBUTEADDRESPONSE = DESCRIPTOR.message_types_by_name['NodeAttributeAddResponse']
CreateChildRequest = _reflection.GeneratedProtocolMessageType('CreateChildRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHILDREQUEST,
  '__module__' : 'freeplane_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.CreateChildRequest)
  })
_sym_db.RegisterMessage(CreateChildRequest)

CreateChildResponse = _reflection.GeneratedProtocolMessageType('CreateChildResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECHILDRESPONSE,
  '__module__' : 'freeplane_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.CreateChildResponse)
  })
_sym_db.RegisterMessage(CreateChildResponse)

DeleteChildRequest = _reflection.GeneratedProtocolMessageType('DeleteChildRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETECHILDREQUEST,
  '__module__' : 'freeplane_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.DeleteChildRequest)
  })
_sym_db.RegisterMessage(DeleteChildRequest)

DeleteChildResponse = _reflection.GeneratedProtocolMessageType('DeleteChildResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETECHILDRESPONSE,
  '__module__' : 'freeplane_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.DeleteChildResponse)
  })
_sym_db.RegisterMessage(DeleteChildResponse)

NodeAttributeAddRequest = _reflection.GeneratedProtocolMessageType('NodeAttributeAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEATTRIBUTEADDREQUEST,
  '__module__' : 'freeplane_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.NodeAttributeAddRequest)
  })
_sym_db.RegisterMessage(NodeAttributeAddRequest)

NodeAttributeAddResponse = _reflection.GeneratedProtocolMessageType('NodeAttributeAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _NODEATTRIBUTEADDRESPONSE,
  '__module__' : 'freeplane_pb2'
  # @@protoc_insertion_point(class_scope:freeplane.NodeAttributeAddResponse)
  })
_sym_db.RegisterMessage(NodeAttributeAddResponse)

_FREEPLANE = DESCRIPTOR.services_by_name['Freeplane']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031org.freeplane.plugin.grpcB\tfreeplaneP\001\242\002\002FP'
  _CREATECHILDREQUEST._serialized_start=30
  _CREATECHILDREQUEST._serialized_end=64
  _CREATECHILDRESPONSE._serialized_start=66
  _CREATECHILDRESPONSE._serialized_end=123
  _DELETECHILDREQUEST._serialized_start=125
  _DELETECHILDREQUEST._serialized_end=162
  _DELETECHILDRESPONSE._serialized_start=164
  _DELETECHILDRESPONSE._serialized_end=202
  _NODEATTRIBUTEADDREQUEST._serialized_start=204
  _NODEATTRIBUTEADDREQUEST._serialized_end=293
  _NODEATTRIBUTEADDRESPONSE._serialized_start=295
  _NODEATTRIBUTEADDRESPONSE._serialized_end=338
  _FREEPLANE._serialized_start=341
  _FREEPLANE._serialized_end=607
# @@protoc_insertion_point(module_scope)
