# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: freeplane.proto for package 'freeplane'

require 'grpc'
require 'freeplane_pb'

module Freeplane
  module Freeplane
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'freeplane.Freeplane'

      rpc :CreateChild, CreateChildRequest, CreateChildResponse
      rpc :DeleteChild, DeleteChildRequest, DeleteChildResponse
    end

    Stub = Service.rpc_stub_class
  end
end
