---
parameters:
  bash:
    functions:
      rabbitmq_payload_prepare: |
        cat<<EOF
        {
           "vhost": "/",
            "name": "",
            "properties": {
        	"delivery_mode": 2,
        	"headers": {}
            },
            "routing_key": "key",
            "delivery_mode": "1",
            "payload":`jq @json`,
            "headers": {},
            "props": {},
            "payload_encoding": "string"
        }
        EOF
      rabbitmq_publish_data: |
        local exchange=$1
        user=${rabbitmq_user}
        pass=${rabbitmq_password}
        #TODO(@metacoma) fix hardcode
        rmq_url="`minikube ip`:32100"
        curl -vu "$user:$pass" -H "Accept: application/json" -H "Content-Type:application/json" -X POST -d @- http://$rmq_url/api/exchanges/%2f/$exchange/publish

      # . functions.bash
      # cat json | rabbitmq_publish_json exchange_name
      rabbitmq_publish_json: |
        local exchange=$1
        rabbitmq_payload_prepare | rabbitmq_publish_data $exchange


  rabbitmq_release_name: rabbitmq
  rabbitmq_default_port: 5672
  rabbitmq_k8s_namespace: rabbitmq
  rabbitmq_exchanges:
    io-line:
      name: io-line
      type: fanout
      durable: true
    io-context:
      name: io-context
      type: fanout
      durable: true
    io-document:
      name: io-document
      type: fanout
      durable: true
    tmux:
      name: tmux
      type: fanout
      durable: true
    openai:
      name: openai
      type: fanout
      durable: true
    mindwm-context:
      name: &mindwm_context_exchange mindwm-context
      type: fanout
      durable: true
    mindwm-document:
      name: &mindwm_document_exchange mindwm-document
      type: fanout
      durable: true
    freeplane-track-context:
      name: freeplane-track-context
      type: fanout
      durable: true

  rabbitmq_queues:
    mindwm-context:
      name: *mindwm_context_exchange
      durable: true
    mindwm-document:
      name: *mindwm_document_exchange
      durable: true


  rabbitmq_bindings:
    mindwm-context:
      exchange_name: *mindwm_context_exchange
      queue_name: *mindwm_context_exchange
      data:
        routing_key: ""
        arguments: {}

    mindwm-document:
      exchange_name: *mindwm_document_exchange
      queue_name: *mindwm_document_exchange
      data:
        routing_key: ""
        arguments: {}

  rabbitmq_version: 3.12.4
  rabbitmq_user: user
  rabbitmq_password: password
