---
classes:
  - rabbitmq.common
  - rabbitmq.helm
parameters:

  rabbitmq_namespace: ${rabbitmq_k8s_namespace}
  rabbitmq_manage_node_port: 32100
  rabbitmq_image:
    repo: bitnami/rabbitmq
    tag: ${rabbitmq_version}-debian-11-r0

  kapitan:
    compile:
      - input_paths:
          - templates/rabbitmq
        output_path: rabbitmq
        input_type: jinja2
