# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freeplane.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "freeplane.CreateChildRequest" do
    optional :name, :string, 1
  end
  add_message "freeplane.CreateChildResponse" do
    optional :message, :string, 1
  end
end

module Freeplane
  CreateChildRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("freeplane.CreateChildRequest").msgclass
  CreateChildResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("freeplane.CreateChildResponse").msgclass
end
