---
parameters:

  opensearch_helm_release: opensearch

  bash:
    functions:
      opensearch_install: |
        local ns=\${1:-${opensearch_k8s_namespace}}
        (
          cd files/helm-charts/opensearch
          helm upgrade ${opensearch_helm_release} \
            --namespace \${ns} \
            --create-namespace \
            --install . -f ${compiled_dir}/helm/opensearch.yaml
        )


  kapitan:
    dependencies:
      - type: helm
        output_path: files/helm-charts/opensearch
        source: https://opensearch-project.github.io/helm-charts/
        chart_name: opensearch
        version: 2.9.0

  # default values for chart
  helm:
    opensearch:
      extraVars:
        - name:  DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
      service:
        type: NodePort
        nodePort: ${opensearch_port}
      singleNode: true

