parameters:
  kapitan:
    compile:
      - input_paths:
          - templates/opensearch/create_index.sh
        output_path: .
        input_type: jinja2

  # tmux-io-context
  opensearch_raw_tmux_io_context_index: "tmux-raw-pane-io-context"
  # without colors codes
  opensearch_tmux_io_context_index: "tmux-pane-io-context"

  # tmux-raw-stream-lines
  opensearch_raw_tmux_lines_index: "tmux-pane-raw-lines"
  # without colors codes
  opensearch_tmux_lines_index: "tmux-pane-lines"

  opensearch_index_patterns:
    opensearch_raw_tmux_io_context_index:
      name: ${opensearch_raw_tmux_io_context_index}
    opensearch_tmux_io_context_index:
      name: ${opensearch_tmux_io_context_index}
    opensearch_raw_tmux_lines_index:
      name: ${opensearch_raw_tmux_lines_index}
    opensearch_tmux_lines_index:
      name: ${opensearch_tmux_lines_index}






  # http basic auth
  opensearch_vector_user: vector
  opensearch_vector_password_hash: '$2y$12$UC0jxOHocXPPNtUxa8Lz3uc6zslO1RU/wAqg0ia1BUqygplRMF4rq' # hash generated by opensearch-security/tools/hash.sh script
  opensearch_vector_password: vectorvector

  # for opensearch api calls
  opensearch_api_user: admin
  opensearch_api_password: admin
  opensearch_api_password_hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG" # hash generated by opensearch-security/tools/hash.sh script
