---
parameters:

  kafka_k8s_namespace: kafka
  kafka_port: 9092

  kafka_version:
    major: 3.3.1
    minor: 2.13
  kafka:
    host: 127.0.0.1
    port: 9092
  kafka_root_dir: ${kapitan_root}/files/kafka

  # this property should be the same with the name of kafka_cluster
  kafka_cluster_name: mindwm     # --.
                                 #   |
  kafka_clusters:                #   |
    mindwm:  # <---------------------'
      # https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml
      kafka:
        version: 3.3.1
        replicas: 1
        listeners:
          - name: external
            port: ${kafka_port}
            type: nodeport
            tls: false
        config:
          offsets.topic.replication.factor: 1
          transaction.state.log.replication.factor: 1
          transaction.state.log.min.isr: 1
          default.replication.factor: 1
          min.insync.replicas: 1
          inter.broker.protocol.version: "3.3"
        storage:
          type: jbod
          volumes:
          - id: 0
            type: persistent-claim
            size: 8Gi
            deleteClaim: true

      zookeeper:
        replicas: 1
        storage:
          type: persistent-claim
          size: 8Gi
          deleteClaim: true
      entityOperator:
        topicOperator: {}
        userOperator: {}

