---
parameters:

  kafka_topics:
    tmux-pane-bytestream:
      # 'spec' https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/topic/kafka-topic.yaml
      name: ${kafka_topic_tmux_bytestream}
      partitions: 1
      replicas: 1
      config:
        retention.ms: 60000 # 60 seconds
        retention.bytes: 536870912 # 512 Mb
