---
parameters:
  kafka_topics:
    tmux-pane-raw-io-context:
      # 'spec' https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/topic/kafka-topic.yaml
      name: ${kafka_topic_tmux_raw_io_context}
      partitions: 1
      replicas: 1
      config:
        retention.ms: 600000 # 600 seconds
        retention.bytes: 536870912 # 512 Mb
