---
parameters:

  mindwm_consumer_base_image: "alpine:3.17"

  kapitan:
    dependencies:
      - source: https://github.com/jsonnet-libs/k8s-libsonnet
        type: git
        output_path: files/github.com/jsonnet-libs/k8s-libsonnet
        ref: 85543e49238903ac14b486321bd3d60fef09d9ef
    compile:
      - input_paths:
          - jsonnet/mindwm/consumer/*.jsonnet
#          - jsonnet/mindwm/consumer
#          - jsonnet/mindwm/consumer
        output_path: mindwm-consumer
        input_type: jsonnet
        output_type: plain
