name: Kapitan
permissions: write-all
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kapitan:
    name: Kapitan fetch and compile
    runs-on: ubuntu-latest
    container:
      image: kapicorp/kapitan:v0.31.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kapitan compile
        run: |
          kapitan compile --fetch
