name: Kapitan Compile
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kapitan:
    name: Terraform 
    runs-on: ubuntu-latest
    container:
      image: kapicorp/kapitan:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kapitan compile
        run: |
          kapitan compile --fetch
