---
classes:
  - helm
  - neo4j.common
parameters:
  neo4j_chart_version: 5.11.0
  neo4j_helm_chart_path: files/helm-charts/neo4j

  bash:
    functions:
      neo4j_helm_install: |
        helm upgrade --install --namespace ${neo4j_namespace} ${neo4j_release_name} ${kapitan_root}/${neo4j_helm_chart_path} -f ${compiled_dir}/helm/values.yaml
      neo4j_helm_delete: |
        helm delete --namespace ${neo4j_namespace} ${neo4j_release_name}
  kapitan:
    dependencies:
      - output_path: ${neo4j_helm_chart_path}
        type: helm
        source: https://helm.neo4j.com/neo4j
        version: ${neo4j_chart_version}
        chart_name: neo4j
